'use client'

import { useState, useEffect } from 'react'
import type { NewsItem, Article } from '@/lib/content'

interface Props {
  initialNews: NewsItem[]
  initialArticles: Article[]
}

const translations = {
  pt: {
    navNoticias: 'Notícias',
    navArtigos: 'Artigos',
    navSobre: 'Sobre',
    heroEyebrow: 'Astronomia & Astrofísica',
    heroTitle: 'De Olho no',
    heroTitleGlow: 'Céu',
    heroSub: 'O universo explicado para todos — notícias e descobertas em linguagem simples.',
    tickerLabel: 'Ao vivo',
    leftPanelTitle: 'Notícias & Descobertas',
    rightPanelTitle: 'Conceitos & Física',
    readMore: 'Ler artigo completo →',
    readOriginal: 'Fonte original',
    minRead: 'min de leitura',
    noNews: 'A automação ainda não gerou notícias. Execute o script Python para popular o site.',
    noArticles: 'A automação ainda não gerou artigos. Execute o script Python para popular o site.',
    footerText: 'De Olho no Céu · Conteúdo gerado automaticamente por IA a partir de fontes científicas confiáveis · Atualizado diariamente',
    concept: '✦ Conceito',
    discovery: '🔭 Descoberta',
  },
  en: {
    navNoticias: 'News',
    navArtigos: 'Articles',
    navSobre: 'About',
    heroEyebrow: 'Astronomy & Astrophysics',
    heroTitle: 'Eye on the',
    heroTitleGlow: 'Sky',
    heroSub: 'The universe explained for everyone — news and discoveries in plain language.',
    tickerLabel: 'Live',
    leftPanelTitle: 'News & Discoveries',
    rightPanelTitle: 'Concepts & Physics',
    readMore: 'Read full article →',
    readOriginal: 'Original source',
    minRead: 'min read',
    noNews: 'Automation has not generated news yet. Run the Python script to populate the site.',
    noArticles: 'Automation has not generated articles yet. Run the Python script to populate the site.',
    footerText: 'Eye on the Sky · Content automatically generated by AI from reliable scientific sources · Updated daily',
    concept: '✦ Concept',
    discovery: '🔭 Discovery',
  }
}

function formatDate(dateStr: string, lang: string): string {
  const d = new Date(dateStr)
  if (lang === 'pt') return d.toLocaleDateString('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' })
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

const TICKER_MESSAGES = {
  pt: [
    '🌌 A Via Láctea contém entre 100 e 400 bilhões de estrelas',
    '🔭 Telescópio James Webb opera a 1,5 milhão km da Terra',
    '⚫ O buraco negro M87* tem massa equivalente a 6,5 bilhões de sóis',
    '🪐 Saturno perderia para a água — sua densidade é menor que a da H₂O',
    '💫 A luz do Sol leva 8 minutos e 20 segundos para chegar à Terra',
    '🌠 Existem mais estrelas no universo do que grãos de areia em todas as praias da Terra',
  ],
  en: [
    '🌌 The Milky Way contains between 100 and 400 billion stars',
    '🔭 James Webb Telescope operates 1.5 million km from Earth',
    '⚫ Black hole M87* has a mass equal to 6.5 billion suns',
    '🪐 Saturn would float on water — its density is lower than H₂O',
    '💫 Sunlight takes 8 minutes 20 seconds to reach Earth',
    '🌠 There are more stars in the universe than grains of sand on all Earth\'s beaches',
  ]
}

export default function HomeClient({ initialNews, initialArticles }: Props) {
  const [lang, setLang] = useState<'pt' | 'en'>('pt')
  const [tickerIdx, setTickerIdx] = useState(0)
  const [expandedArticle, setExpandedArticle] = useState<string | null>(null)
  const t = translations[lang]

  useEffect(() => {
    const interval = setInterval(() => {
      setTickerIdx(i => (i + 1) % TICKER_MESSAGES[lang].length)
    }, 6000)
    return () => clearInterval(interval)
  }, [lang])

  const tickerMessages = TICKER_MESSAGES[lang]

  return (
    <>
      {/* HEADER */}
      <header className="site-header">
        <a href="/" className="header-logo">
          <div className="logo-icon" />
          <span className="logo-text">
            {lang === 'pt' ? 'De Olho no ' : 'Eye on the '}
            <span>{lang === 'pt' ? 'Céu' : 'Sky'}</span>
          </span>
        </a>
        <nav className="header-nav">
          <a href="#noticias">{t.navNoticias}</a>
          <a href="#artigos">{t.navArtigos}</a>
          <a href="#sobre">{t.navSobre}</a>
        </nav>
        <div className="lang-toggle">
          <button className={`lang-btn ${lang === 'pt' ? 'active' : ''}`} onClick={() => setLang('pt')}>PT</button>
          <button className={`lang-btn ${lang === 'en' ? 'active' : ''}`} onClick={() => setLang('en')}>EN</button>
        </div>
      </header>

      {/* HERO */}
      <div className="hero-banner">
        <div className="hero-eyebrow">{t.heroEyebrow}</div>
        <h1 className="hero-title">
          {t.heroTitle} <span className="glow">{t.heroTitleGlow}</span>
        </h1>
        <p className="hero-subtitle">{t.heroSub}</p>
      </div>

      {/* TICKER */}
      <div className="live-ticker">
        <span className="ticker-label">{t.tickerLabel}</span>
        <span className="ticker-dot" />
        <span className="ticker-text">
          <strong>{tickerMessages[tickerIdx]}</strong>
        </span>
      </div>

      {/* MAIN TWO-PANEL GRID */}
      <main className="main-grid">

        {/* ── LEFT: NOTÍCIAS ── */}
        <section className="panel-left" id="noticias">
          <div className="panel-header">
            <div className="panel-title">
              <span className="panel-title-icon">📡</span>
              {t.leftPanelTitle}
            </div>
            <span className="panel-count">{initialNews.length} itens</span>
          </div>

          {/* Ad slot */}
          <div className="ad-slot">
            <span className="ad-slot-label">PUBLICIDADE · ADVERTISEMENT</span>
          </div>

          {initialNews.length === 0 ? (
            <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', padding: '2rem 0', textAlign: 'center' }}>
              {t.noNews}
            </div>
          ) : (
            initialNews.map(item => (
              <article className="news-card" key={item.slug}>
                <div className="news-card-meta">
                  <span className={`news-source ${item.sourceType}`}>{item.source}</span>
                  <span className="news-date">{formatDate(item.date, lang)}</span>
                </div>
                <h2 className="news-title">
                  {lang === 'pt' ? item.title : (item.titleEn || item.title)}
                </h2>
                <p className="news-excerpt">
                  {lang === 'pt' ? item.excerpt : (item.excerptEn || item.excerpt)}
                </p>
                {item.tags && (
                  <div className="news-tags">
                    {item.tags.map(tag => (
                      <span className="news-tag" key={tag}>{tag}</span>
                    ))}
                  </div>
                )}
                <a
                  href={item.sourceUrl}
                  className="news-link"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {t.readOriginal} ↗
                </a>
              </article>
            ))
          )}
        </section>

        {/* ── RIGHT: ARTIGOS ── */}
        <section className="panel-right" id="artigos">
          <div className="panel-header">
            <div className="panel-title">
              <span className="panel-title-icon">✨</span>
              {t.rightPanelTitle}
            </div>
            <span className="panel-count">{initialArticles.length} artigos</span>
          </div>

          {/* Ad slot */}
          <div className="ad-slot">
            <span className="ad-slot-label">PUBLICIDADE · ADVERTISEMENT</span>
          </div>

          {initialArticles.length === 0 ? (
            <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', padding: '2rem 0', textAlign: 'center' }}>
              {t.noArticles}
            </div>
          ) : (
            initialArticles.map(item => {
              const isExpanded = expandedArticle === item.slug
              const body = lang === 'pt' ? item.content : (item.contentEn || item.content)
              const title = lang === 'pt' ? item.title : (item.titleEn || item.title)
              const category = lang === 'pt' ? item.category : (item.categoryEn || item.category)

              return (
                <article className="article-card" key={item.slug}>
                  <div className="article-badge">
                    <span className={item.type === 'concept' ? 'badge-concept' : 'badge-news-art'}>
                      {item.type === 'concept' ? t.concept : t.discovery}
                    </span>
                    <span style={{ color: 'var(--text-muted)', fontSize: '0.6rem' }}>
                      {category} · {formatDate(item.date, lang)}
                    </span>
                  </div>
                  <h2 className="article-title">{title}</h2>
                  <div className="article-reading-time">
                    ⏱ {item.readingTime} {t.minRead}
                  </div>
                  <div className="article-body">
                    {isExpanded
                      ? body.split('\n\n').map((p, i) => <p key={i}>{p}</p>)
                      : body.split('\n\n').slice(0, 2).map((p, i) => <p key={i}>{p}</p>)
                    }
                  </div>
                  <button
                    className="read-more-btn"
                    onClick={() => setExpandedArticle(isExpanded ? null : item.slug)}
                  >
                    {isExpanded ? '← Menos' : t.readMore}
                  </button>
                </article>
              )
            })
          )}
        </section>
      </main>

      {/* ABOUT SECTION */}
      <section id="sobre" style={{
        background: 'var(--panel-dark)',
        borderTop: '1px solid var(--border-dim)',
        padding: '2rem 1.5rem',
        position: 'relative',
        zIndex: 1
      }}>
        <div style={{ maxWidth: '700px', margin: '0 auto', textAlign: 'center' }}>
          <p style={{
            fontFamily: "'Space Mono', monospace",
            fontSize: '0.65rem',
            letterSpacing: '0.14em',
            color: 'var(--aurora-cyan)',
            textTransform: 'uppercase',
            marginBottom: '0.75rem'
          }}>
            {lang === 'pt' ? 'Sobre o projeto' : 'About'}
          </p>
          <p style={{ fontFamily: "'Crimson Pro', serif", fontSize: '1rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
            {lang === 'pt'
              ? 'De Olho no Céu reúne automaticamente notícias de fontes como NASA, ESA, Space.com e o Centro de Ciência Viva do Algarve, e usa inteligência artificial para reescrever cada descoberta em linguagem acessível — sem fórmulas, sem jargão. Dois artigos conceituais sobre física e astrofísica são publicados todos os dias.'
              : 'Eye on the Sky automatically gathers news from sources such as NASA, ESA, Space.com and the Algarve Living Science Centre, and uses artificial intelligence to rewrite each discovery in plain language — no formulas, no jargon. Two conceptual articles on physics and astrophysics are published every day.'
            }
          </p>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="site-footer">
        <p className="footer-text">{t.footerText}</p>
      </footer>
    </>
  )
}
